### PR TITLE
implmented syntax highlighting for vim

### PR DESCRIPTION
**Pull request by Inphi**
Syntax highlighting for the documented grammar at ark-lang/ark@36e99dae08

### CODE REVIEW

**Comment by MovingtoMars** [comment]
Thank you so much!

Could you just do one thing first, though: remove `float` and `double` as keywords, they're not in the language anymore because they were just duplicates of `f32` and `f64`.

Once you've done that I'll merge.

**Comment by Inphi** [comment]
what else do you need?

**Comment by MovingtoMars** [comment]
Ah, I just forgot, sorry...

**Comment by felixangell** [comment]
:+1:

**Pull request merged**
